name: test

on: push

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install zsh
      - run: make test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
